# Chapter 7: NumPy for Data Analysis

**Goal**: Master NumPy – the numerical engine behind Pandas, Scikit-learn and almost every data library.

Why NumPy for MBA Analysts?
- Extremely fast array operations (vectorization)
- Foundation of all modern data science tools
- Perfect for financial calculations, simulations, and matrix operations

---

## 8.1 Creating Arrays

In [1]:
import numpy as np

# From list
sales = np.array([125, 98, 112, 145, 130, 160])
print(sales)
print(type(sales))
print(sales.dtype)

[125  98 112 145 130 160]
<class 'numpy.ndarray'>
int64


In [2]:
# Multi-dimensional (matrix)
region_month = np.array([
    [125, 130, 140],   # North
    [98, 105, 110],    # South
    [112, 115, 125],   # East
    [145, 150, 160]    # West
])
print(region_month)
print("Shape:", region_month.shape)   # (rows, columns)

[[125 130 140]
 [ 98 105 110]
 [112 115 125]
 [145 150 160]]
Shape: (4, 3)


In [3]:
# Special arrays
print(np.zeros((3, 4)))
print(np.ones((2, 5)))
print(np.arange(0, 11, 2))
print(np.linspace(0, 1, 5))          # 5 evenly spaced numbers between 0 and 1
print(np.random.rand(3, 3))          # Random numbers [0,1)
print(np.random.randint(50, 150, size=(3, 4)))  # Random integers

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  2  4  6  8 10]
[0.   0.25 0.5  0.75 1.  ]
[[0.43274143 0.02786425 0.6340419 ]
 [0.83060797 0.04615826 0.11991745]
 [0.27171681 0.11608507 0.93769717]]
[[112  51  64  54]
 [ 69  55 113  94]
 [118  71  97  66]]


---

## 8.2 Array Operations (Vectorization – The Superpower)

In [4]:
sales = np.array([125, 98, 112, 145, 130, 160])
targets = np.array([120, 100, 110, 140, 125, 150])

# Element-wise operations (no loops needed!)
print("Difference :", sales - targets)
print("Achievement %:", (sales / targets) * 100)
print("Growth +10% :", sales * 1.1)

Difference : [ 5 -2  2  5  5 10]
Achievement %: [104.16666667  98.         101.81818182 103.57142857 104.
 106.66666667]
Growth +10% : [137.5 107.8 123.2 159.5 143.  176. ]


In [5]:
# Aggregations
print("Total sales :", sales.sum())
print("Average     :", sales.mean())
print("Max         :", sales.max())
print("Min         :", sales.min())
print("Std Dev     :", sales.std())
print("Variance    :", sales.var())

Total sales : 770
Average     : 128.33333333333334
Max         : 160
Min         : 98
Std Dev     : 20.33606539022619
Variance    : 413.5555555555555


---

## 8.3 Indexing, Slicing & Boolean Masking

In [6]:
print(sales[0])
print(sales[1:4])
print(sales[-3:])

# Boolean masking – extremely powerful
print(sales > 120)
print(sales[sales > 120])           # Only high performers
print(sales[(sales > 100) & (sales < 140)])

125
[ 98 112 145]
[145 130 160]
[ True False False  True  True  True]
[125 145 130 160]
[125 112 130]


In [7]:
# 2D indexing
print(region_month[0])          # First row (North)
print(region_month[:, 1])       # Second column (all regions, month 2)
print(region_month[1:3, 0:2])   # Sub-matrix

[125 130 140]
[130 105 115 150]
[[ 98 105]
 [112 115]]


---

## 8.4 Reshaping & Useful Functions

In [8]:
arr = np.arange(12)
print(arr)
print(arr.reshape(3, 4))
print(arr.reshape(2, 6))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [9]:
# Statistical functions along axes
print("Row-wise mean (each region):", region_month.mean(axis=1))
print("Column-wise mean (each month):", region_month.mean(axis=0))

Row-wise mean (each region): [131.66666667 104.33333333 117.33333333 151.66666667]
Column-wise mean (each month): [120.   125.   133.75]


---

## 8.5 Business Mini-Case: Portfolio Return Simulation

In [10]:
# Simulate 5 years of monthly returns for a portfolio
np.random.seed(42)
monthly_returns = np.random.normal(loc=0.01, scale=0.04, size=60)  # 5 years

cumulative = np.cumprod(1 + monthly_returns)
final_value = 1000000 * cumulative[-1]

print(f"Starting Capital : ₹10,00,000")
print(f"Final Value      : ₹{final_value:,.0f}")
print(f"Total Return     : {(final_value/1000000 - 1)*100:.1f}%")
print(f"Best Month       : {monthly_returns.max()*100:.1f}%")
print(f"Worst Month      : {monthly_returns.min()*100:.1f}%")
print(f"Average Monthly  : {monthly_returns.mean()*100:.2f}%")

Starting Capital : ₹10,00,000
Final Value      : ₹1,208,870
Total Return     : 20.9%
Best Month       : 8.4%
Worst Month      : -6.8%
Average Monthly  : 0.38%


---

## Business Challenge – Chapter 7

You have sales data for 4 regions across 6 months (in lakhs):

```python
data = np.array([
    [45, 48, 52, 49, 55, 60],   # North
    [38, 40, 42, 41, 45, 48],   # South
    [42, 44, 47, 46, 50, 53],   # East
    [50, 53, 58, 55, 62, 65]    # West
])
```

**Tasks**:
1. Calculate total sales per region and per month.
2. Find the region with highest average sales.
3. Calculate month-over-month growth for the West region.
4. Identify all values above 55 (high performance months).
5. Compute overall mean, median and standard deviation.

In [11]:
# Your solution here
import numpy as np


---

## Key Takeaways
- NumPy arrays are fast and support vectorized operations.
- Boolean masking is one of the most powerful features.
- Almost every data library (Pandas, Scikit-learn) is built on NumPy.

**Next Chapter**: Pandas – The Most Important Library for MBA Data Analysts